name: Changesets
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      # config recommended by pnpm error
      - run: pnpm config set store-dir "/home/runner/setup-pnpm/node_modules/.bin/store/v3" --global

      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test

      - name: Update and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: new release"
          title: "chore: new release candidate"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
