name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - run: pnpm install && pnpm build
      - run: pnpm lint && pnpm test
