name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      # config recommended by pnpm error
      - run: pnpm config set store-dir "/home/runner/setup-pnpm/node_modules/.bin/store/v3" --global

      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
